// <auto-generated />
namespace PayLab_BP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingTenantType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingTenantType));
        
        string IMigrationMetadata.Id
        {
            get { return "201701092101002_AddingTenantType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
